### ISSUE TITLE
scalarAvection does not exit with an error if wrong executor name is chosen

### ISSUE THREAD

**Issue by happyKitesurfer** [exasim-project/FoamAdapter#22]
I wrote in the control dict 

executor        LPU;

However the application does not crash as supposed in setup.cpp:

NeoFOAM::Executor createExecutor(const dictionary& dict)
{
    auto execName = dict.get<word>("executor");

    Info << execName << nl;

    if (execName == "Serial")
    {
        Info << "Serial executor chosen" << nl;
        return NeoFOAM::SerialExecutor();
    }
    else if (execName == "CPU")
    {
        Info << "CPU executor chosen" << nl;
        return NeoFOAM::CPUExecutor();
    }
    else if (execName == "GPU")
    {
        Info << "GPU executor chosen" << nl;
        return NeoFOAM::GPUExecutor();
    }
    else
    {
        FatalError << "Executor not recognized" << endl;
    }
    Info << "executor chosen" << endl;
    Info << execName << nl;
    return NeoFOAM::SerialExecutor();
}

It actually goes always to the end of the if else conditions

**Comment by happyKitesurfer** [comment]
Even if I type 

executor GPU;

in the controlDict It goes to the end of the if else conditions

**Comment by happyKitesurfer** [comment]
I think dict.get<word>("executor");

returns a word object, i.e., https://www.openfoam.com/documentation/guides/latest/api/classFoam_1_1word.html.

Maybe the == operator gets fooled :)

**Comment by happyKitesurfer** [comment]
Ok the topic of comparing word with string was already discussed here:

https://www.cfd-online.com/Forums/openfoam-programming-development/168446-compare-word-variable-string.html

the solution is to convert the string to a word and compare to the dictionary entry

**Comment by greole** [comment]
Thanks for reporting!

**Comment by HenningScheufler** [comment]
Does this fixes the issue:

https://github.com/exasim-project/FoamAdapter/blob/fe4f53f050e31a5fd1d0a141df2fd64f316c4bca/src/setup/setup.cpp

**Comment by happyKitesurfer** [comment]
I had to convert the strings "CPU", "GPU" and "Serial" to word before the == operator worked:


NeoFOAM::Executor createExecutor(const dictionary& dict)
{

    word execName = dict.get<word>("executor");


    word Serial("Serial") ;
    word CPU("CPU") ;
    word GPU("GPU") ;

    Info << execName << nl;

    if (execName == Serial)
    {
        Info << "Serial executor chosen" << nl;
        return NeoFOAM::SerialExecutor();
    }
    else if (execName == CPU)
    {
        Info << "CPU executor chosen" << nl;
        return NeoFOAM::CPUExecutor();
    }
    else if (execName == GPU)
    {
        Info << "GPU executor chosen" << nl;
        return NeoFOAM::GPUExecutor();
    }
    else
    {
        FatalError << "Executor not recognized" << endl;
    }
    Info << "chosen" << endl;
    Info << execName << nl;
    return NeoFOAM::SerialExecutor();
}
