### ISSUE TITLE
Ambiguous overloading of transcendental function in scalarAdvection

### ISSUE THREAD

**Issue by gregorweiss** [exasim-project/FoamAdapter#26]
OS: Rocky 9.4
Compiler: clang 18.24.05 with CUDA 12.4
Kokkos: 4.5 (current develop branch)
OF: v2406

When compiling examples, namely, scalarAdvection overloading of sin/exp/cos throw amiguity errors
```
In file included from /usr/local/cuda-12.4/include/crt/math_functions.h:12199,
                 from /usr/local/cuda-12.4/include/crt/common_functions.h:303,
                 from /usr/local/cuda-12.4/include/crt/host_runtime.h:285,
                 from /tmp/tmpxft_000ab31e_00000000-6_scalarAdvection.cudafe1.stub.c:8,
                 from tmpxft_000ab31e_00000000-6_scalarAdvection.cudafe1.stub.c:1:
/usr/local/cuda-12.4/include/crt/math_functions.hpp: In function ‘double rsqrt(double)’:
/usr/local/cuda-12.4/include/crt/math_functions.hpp:2955:20: error: call of overloaded ‘sqrt(const double&)’ is ambiguous
 2955 |   return 1.0 / sqrt(a);
      |                ~~~~^~~
/usr/include/bits/mathcalls.h:143:15: note: candidate: ‘double sqrt(double)’
  143 | __MATHCALL (sqrt,, (_Mdouble_ __x));
      |               ^~~~
/usr/include/c++/11/cmath:467:23: note: candidate: ‘constexpr long double std::sqrt(long double)’
  467 |   sqrt(long double __x)
      |                       ^   
/usr/include/c++/11/cmath:463:17: note: candidate: ‘constexpr float std::sqrt(float)’
  463 |   sqrt(float __x)
      |                 ^   
~/code/openfoam/source/src/OpenFOAM/lnInclude/Scalar.H:187:20: note: candidate: ‘Foam::floatScalar Foam::sqrt(Foam::floatScalar)’
  187 | transFunc(sqrt)
      |                    ^   
~/code/openfoam/source/src/OpenFOAM/lnInclude/Scalar.H:187:21: note: candidate: ‘Foam::doubleScalar Foam::sqrt(Foam::doubleScalar)’
  187 | transFunc(sqrt)
      |                     ^   
~/code/openfoam/source/src/OpenFOAM/lnInclude/dimensionedScalar.H:68:19: note: candidate: ‘Foam::dimensionedScalar Foam::sqrt(const dimensionedScalar&)’
   68 | dimensionedScalar sqrt(const dimensionedScalar&);
      |         
```

So, seems to clash with definitions in CUDA, C++ std math, and Foam namespace.

Have you seen something similar, before?

**Comment by happyKitesurfer** [comment]
I could fix the compilation in scalarAdvection removing the using namespace Foam:

//using namespace Foam;

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //
namespace fvcc = NeoFOAM::finiteVolume::cellCentred;

int main(int argc, char* argv[])
{
    Kokkos::initialize(argc, argv);
    {
#include "addCheckCaseOptions.H"
#include "setRootCase.H"
#include "createTime.H"
#include "createNFTime.H"
#include "createControl.H"
#include "createFields.H"

        Foam::Info << "creating NeoFOAM mesh" << Foam::endl;
        auto nfMesh = mesh.nfMesh();


That removed the compiler error in the scalarAdvection. The errors compiling the tests still exists. I cannot figure out where the Foam namespace is used.

**Comment by HenningScheufler** [comment]
possible fix in PR #28

**Comment by HenningScheufler** [comment]
should be fixed

**Comment by happyKitesurfer** [comment]
Hello, I tested the fix and the compilation worked. By the way what does the line

#define namespaceFoam

do? I never saw a #define statement followed only by one statement

**Comment by happyKitesurfer** [comment]
Now I get this: 

#1  Foam::sigSegv::sigHandler(int) in ~/OpenFoam/OpenFOAM-v2406/platforms/linux64GccDPInt32Opt/lib/libOpenFOAM.so
#2  ? in /lib/x86_64-linux-gnu/libc.so.6
#3  Foam::convert(double const&) at ~/NeoFOAM/FoamAdapter/src/conversion/convert.cpp:11
#4  ? in ~/NeoFOAM/FoamAdapter/build/develop/bin/scalarAdvection
#5  ? in ~/NeoFOAM/FoamAdapter/build/develop/bin/scalarAdvection
#6  ? in ~/NeoFOAM/FoamAdapter/build/develop/bin/scalarAdvection
#7  ? in /lib/x86_64-linux-gnu/libc.so.6
#8  __libc_start_main in /lib/x86_64-linux-gnu/libc.so.6
#9  ? in ~/NeoFOAM/FoamAdapter/build/develop/bin/scalarAdvection
=============
Speicherzugriffsfehler (Speicherabzug geschrieben)

**Comment by happyKitesurfer** [comment]
It happens only when I execute on GPU. I'll try to figure out what's happening

**Comment by happyKitesurfer** [comment]
It always happens at time 0.1 independently  of the size of the mesh (I tries 100 and 1000)

Time = 0.1
max(phi) [0 3 -1 0 0 0 0] 0
max(U) [0 1 -1 0 0 0 0] (0 0 0)
writing nfT field
[stack trace]

**Comment by happyKitesurfer** [comment]
I happens when writing the fields to the harddrive

**Comment by HenningScheufler** [comment]
I will have a look

**Comment by HenningScheufler** [comment]
I fixed the issue in PR #30. CPU tried to access GPU memory ... 

With the release of NeoFoam 0.1, fixes on the other branches will be merged in FoamAdapter

**Comment by greole** [comment]
> > Hello, I tested the fix and the compilation worked. By the way what does the line
> > 
> > #define namespaceFoam
> > 
> > do? I never saw a #define statement followed only by one statement
> 
> With #define namespaceFoam, using namespace Foam is not used in #include fvCFD.H
> 
> https://www.openfoam.com/documentation/guides/latest/api/fvCFD_8H_source.html

We could also move that to CMakeLists.txt

**Comment by gregorweiss** [comment]
Compilation of scalarAdvector (,tests, and benchmarks) works now and scalarAdvector runs fine with #30. Thanks.

**Comment by greole** [comment]
@gregorweiss good to know! Please note that the benchmark case of scalarAdvection currently has uniform (zero everywhere) boundary conditions. I'll try to add something useful soon.
